apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: xbkj6uabf-nodejs 
  janus-idp.io/tekton: xbkj6uabf-nodejs
  backstage.io/kubernetes-id: xbkj6uabf-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xbkj6uabf-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml