apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: xbkj6uabf-nodejs-gitops
  description: This is GitOps manifest for xbkj6uabf-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=xbkj6uabf-nodejs
    backstage.io/kubernetes-id: xbkj6uabf-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: xbkj6uabf-nodejs
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:xbkj6uabf-nodejs
