apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xbkj6uabf-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:2f1d39869e5f1b38213272611dfcc8ee3a4646d0@sha256:6b96d496bc7a347ff4bd46ed44c694f7eb04e3ca8d7f9fc877ef02f68eab290d
          name: container-image
