apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: xbkj6uabf-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: xbkj6uabf-nodejs 
  name: xbkj6uabf-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: xbkj6uabf-nodejs 
